# Generated by Django 2.1 on 2019-08-07 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190806_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 7, 18, 57, 121795, tzinfo=utc)),
        ),
    ]
